### ISSUE TITLE
[공용] Github Settings

### ISSUE THREAD

**Issue by kdh-92** [kdh-92/geojisekki#24]
- [x] main branch protect 셋팅 (해림)
- [x] PR 셋팅 (동현)

**Comment by kdh-92** [comment]
main branch protect 셋팅과 PR 셋팅이 같은거였다고 합니다....ㅎ (완료)

**Comment by kdh-92** [comment]
@Jeong-hae-rim @seyoonkim48 
셋팅 했던 내용은 6.23 스몰톡에서 공유드리고 추후 테스팅 추가하는게  있는데 요걸 부탁드리겠습니다 :)

**Comment by Jeong-hae-rim** [comment]
넵!! 확인했습니다! 이따 스몰톡에서 뵐게요!
